CREATE PROCEDURE FI_SP_IncBeneficiario
    @CPF VARCHAR(14),
    @Nome VARCHAR(100),
    @IdCliente INT
AS
BEGIN
    INSERT INTO BENEFICIARIOS (CPF, NOME, IDCLIENTE)
    VALUES (@CPF, @Nome, @IdCliente);
END